<?php
/**
 * Magendoo Faq Hreflang Template
 *
 * @category  Magendoo
 * @package   Magendoo_Faq
 * @copyright Copyright (c) Magendoo (https://magendoo.ro)
 * @license   https://opensource.org/licenses/MIT MIT License
 */

/** @var \Magendoo\Faq\Block\Faq\Hreflang $block */
?>
<?php $links = $block->getHreflangLinks(); ?>
<?php foreach ($links as $link): ?>
<link rel="alternate" hreflang="<?= $escaper->escapeHtmlAttr($link['hreflang']) ?>" href="<?= $escaper->escapeUrl($link['href']) ?>"/>
<?php endforeach; ?>
