<?php
/**
 * Magendoo Faq Structured Data Template
 *
 * @category  Magendoo
 * @package   Magendoo_Faq
 * @copyright Copyright (c) Magendoo (https://magendoo.ro)
 * @license   https://opensource.org/licenses/MIT MIT License
 */

/** @var \Magendoo\Faq\Block\Faq\StructuredData $block */
?>
<?php $jsonLd = $block->getStructuredDataJson(); ?>
<?php if ($jsonLd): ?>
<script type="application/ld+json">
<?= /* @noEscape */ $jsonLd ?>
</script>
<?php endif; ?>
