<?php
/**
 * Magendoo Faq Question View Template
 *
 * @category  Magendoo
 * @package   Magendoo_Faq
 * @copyright Copyright (c) Magendoo (https://magendoo.ro)
 * @license   https://opensource.org/licenses/MIT MIT License
 */

/** @var \Magendoo\Faq\Block\Faq\Question\View $block */
?>
<?php $question = $block->getQuestion(); ?>
<?php if ($question): ?>
<div class="faq-question-view">
    <?php /* Page title rendered by default Magento page-title-wrapper block. */ ?>

    <div class="faq-full-answer">
        <?= /* @noEscape */ $question->getFullAnswer() ?>
    </div>

    <?= $block->getChildHtml('rating') ?>
    <?= $block->getChildHtml('social') ?>
</div>
<?php endif; ?>
